package vatm.aerosync.worker.atfm;

import org.junit.jupiter.api.Test;
import vatm.aerosync.worker.config.AtfmDatabaseProperties;
import vatm.aerosync.worker.model.ScheduleFlight;
import vatm.aerosync.worker.model.SchedulePermit;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.time.LocalDate;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class JdbcAtfmScheduleGatewayTest {

    @Test
    void truncateUtf8_limitsOracleVarcharValuesByBytesWithoutSplittingCharacters() {
        String value = "A".repeat(3997) + "Việt Nam";

        String truncated = JdbcAtfmScheduleGateway.truncateUtf8(value, 4000);

        assertThat(truncated.getBytes(StandardCharsets.UTF_8)).hasSizeLessThanOrEqualTo(4000);
        assertThat(truncated).isEqualTo("A".repeat(3997) + "Vi");
    }

    @Test
    void truncateUtf8_preservesNullAndValuesWithinTheLimit() {
        assertThat(JdbcAtfmScheduleGateway.truncateUtf8(null, 4000)).isNull();
        assertThat(JdbcAtfmScheduleGateway.truncateUtf8("Nội dung", 4000))
                .isEqualTo("Nội dung");
    }
    @Test
    void update_appendsOnlyMissingDetailsToTheExistingPermId() throws Exception {
        AtfmDatabaseProperties properties = new AtfmDatabaseProperties();
        properties.setUrl("jdbc:h2:mem:atfm-append-" + System.nanoTime()
                + ";MODE=Oracle;DB_CLOSE_DELAY=-1");
        properties.setUsername("sa");
        properties.setPassword("");
        try (Connection connection = DriverManager.getConnection(
                properties.getUrl(), properties.getUsername(), properties.getPassword())) {
            connection.createStatement().execute("CREATE TABLE M_FPAUTHOR (AUTHOR_CODE VARCHAR2(20))");
            connection.createStatement().execute("CREATE TABLE M_OPER (OPER_ICAO VARCHAR2(20))");
            connection.createStatement().execute("CREATE TABLE M_FLY_PURPOSE (PURPOSE_CODE VARCHAR2(20))");
            connection.createStatement().execute("CREATE TABLE M_CRAFT_TYPE (CRAFT_ID NUMBER)");
            connection.createStatement().execute("INSERT INTO M_FPAUTHOR VALUES ('CHK')");
            connection.createStatement().execute("INSERT INTO M_OPER VALUES ('RMY')");
            connection.createStatement().execute("INSERT INTO M_FLY_PURPOSE VALUES ('CAR')");
            connection.createStatement().execute("INSERT INTO M_CRAFT_TYPE VALUES (1935)");
            connection.createStatement().execute("""
                    CREATE TABLE T_PERMMASTER_SC (
                        ID NUMBER PRIMARY KEY, PERM_ID NUMBER NOT NULL,
                        PERMNBR_ID VARCHAR2(100), AUTHOR_ID VARCHAR2(20),
                        PERMTYPE VARCHAR2(20), PERMNBR VARCHAR2(20), VERSION VARCHAR2(20),
                        SEASON VARCHAR2(20), PERMDATE DATE, OPER_ID VARCHAR2(20),
                        REFERENCE VARCHAR2(4000), VALIDHOURS NUMBER, LASTMODIFY TIMESTAMP,
                        LASTUSER VARCHAR2(50), STATUS VARCHAR2(20), PERMCONTENT VARCHAR2(4000),
                        BILLINGADDRESS VARCHAR2(4000), FLIGHTTYPE VARCHAR2(20))
                    """);
            connection.createStatement().execute("""
                    CREATE TABLE T_PERMDETAIL_SC (
                        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        PERM_ID NUMBER NOT NULL, PURPOSE_ID VARCHAR2(20), CRAFT_ID NUMBER,
                        MTOW NUMBER, FLIGHTNBR VARCHAR2(30), REGISTRATION VARCHAR2(100),
                        DAY1 VARCHAR2(1), DAY2 VARCHAR2(1), DAY3 VARCHAR2(1), DAY4 VARCHAR2(1),
                        DAY5 VARCHAR2(1), DAY6 VARCHAR2(1), DAY7 VARCHAR2(1),
                        FROM_AIRP VARCHAR2(10), TO_AIRP VARCHAR2(10), ETD VARCHAR2(10),
                        ETA VARCHAR2(10), VIA VARCHAR2(4000), STATUS VARCHAR2(20),
                        LASTMODIFY TIMESTAMP, LASTUSER VARCHAR2(50), BEGINDATE DATE,
                        ENDDATE DATE, REMARK VARCHAR2(4000))
                    """);
            connection.createStatement().execute("""
                    INSERT INTO T_PERMMASTER_SC (
                        ID, PERM_ID, PERMNBR_ID, AUTHOR_ID, PERMTYPE, PERMNBR,
                        VERSION, SEASON, PERMDATE, OPER_ID, VALIDHOURS, FLIGHTTYPE)
                    VALUES (4167, 9001, 'O/F 05199/S/CHK/2026', 'CHK', 'O/F', '5199',
                            'A', 'S', DATE '2026-07-17', 'RMY', 72, 'SC')
                    """);
            connection.createStatement().execute("""
                    INSERT INTO T_PERMDETAIL_SC (
                        PERM_ID, PURPOSE_ID, CRAFT_ID, MTOW, FLIGHTNBR, REGISTRATION,
                        DAY1, DAY2, DAY3, DAY4, DAY5, DAY6, DAY7,
                        FROM_AIRP, TO_AIRP, ETD, ETA, VIA, STATUS,
                        BEGINDATE, ENDDATE, REMARK)
                    VALUES (9001, 'CAR', 1935, 0, 'RMY685', NULL,
                            '1', '0', '0', '0', '0', '0', '0',
                            'WMKK', 'VHHH', '1140', NULL, 'M765/M771', '0',
                            DATE '2026-07-20', DATE '2026-07-27', 'CAR 76X/32X')
                    """);
        }

        JdbcAtfmScheduleGateway gateway = new JdbcAtfmScheduleGateway(
                properties, new AtfmAirportCodeResolver());
        ScheduleFlight existing = flight("RMY685", "1140");
        ScheduleFlight added = flight("RMY686", "1540");
        SchedulePermit permit = new SchedulePermit(
                "OF-5199/7/2026VN", "O/F 05199/S/CHK/2026", "5199",
                "CHK", "O/F", "A", "S", LocalDate.of(2026, 7, 17),
                "RMY", "G17.44", 72, "Cyberjaya", "SC", "raw",
                List.of(existing, added));

        AtfmWriteResult result = gateway.update(permit);

        assertThat(result.masterId()).isEqualTo(4167L);
        assertThat(result.permId()).isEqualTo(9001L);
        assertThat(result.detailCount()).isOne();
        try (Connection connection = DriverManager.getConnection(
                properties.getUrl(), properties.getUsername(), properties.getPassword());
             var rows = connection.createStatement().executeQuery("""
                     SELECT COUNT(*) AS TOTAL,
                            SUM(CASE WHEN FLIGHTNBR = 'RMY685' THEN 1 ELSE 0 END) AS OLD_ROWS,
                            SUM(CASE WHEN FLIGHTNBR = 'RMY686' THEN 1 ELSE 0 END) AS NEW_ROWS
                       FROM T_PERMDETAIL_SC
                      WHERE PERM_ID = 9001
                     """)) {
            rows.next();
            assertThat(rows.getInt("TOTAL")).isEqualTo(2);
            assertThat(rows.getInt("OLD_ROWS")).isOne();
            assertThat(rows.getInt("NEW_ROWS")).isOne();
        }
    }

    private ScheduleFlight flight(String flightNumber, String etd) {
        return new ScheduleFlight(
                "CAR", 1935L, BigDecimal.ZERO, flightNumber, null, "1000000",
                "WMKK", "VHHH", etd, null, "M765/M771",
                LocalDate.of(2026, 7, 20), LocalDate.of(2026, 7, 27), "CAR 76X/32X");
    }
}
