WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET ECHO OFF
SET FEEDBACK ON
SET VERIFY OFF
SET SERVEROUTPUT ON

PROMPT
PROMPT Initializing AeroSync objects in the connected Oracle schema...

DECLARE
    PROCEDURE create_table_if_missing(
        table_name_in VARCHAR2,
        table_ddl_in  VARCHAR2
    ) IS
        object_count NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO object_count
          FROM user_tables
         WHERE table_name = UPPER(table_name_in);

        IF object_count = 0 THEN
            EXECUTE IMMEDIATE table_ddl_in;
            DBMS_OUTPUT.PUT_LINE('Created table ' || UPPER(table_name_in));
        ELSE
            DBMS_OUTPUT.PUT_LINE('Kept existing table ' || UPPER(table_name_in));
        END IF;
    END;

    PROCEDURE create_sequence_if_missing(
        sequence_name_in VARCHAR2,
        sequence_ddl_in  VARCHAR2
    ) IS
        object_count NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO object_count
          FROM user_sequences
         WHERE sequence_name = UPPER(sequence_name_in);

        IF object_count = 0 THEN
            EXECUTE IMMEDIATE sequence_ddl_in;
            DBMS_OUTPUT.PUT_LINE('Created sequence ' || UPPER(sequence_name_in));
        ELSE
            DBMS_OUTPUT.PUT_LINE('Kept existing sequence ' || UPPER(sequence_name_in));
        END IF;
    END;

    PROCEDURE create_index_if_missing(
        index_name_in VARCHAR2,
        index_ddl_in  VARCHAR2
    ) IS
        object_count NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO object_count
          FROM user_indexes
         WHERE index_name = UPPER(index_name_in);

        IF object_count = 0 THEN
            EXECUTE IMMEDIATE index_ddl_in;
            DBMS_OUTPUT.PUT_LINE('Created index ' || UPPER(index_name_in));
        ELSE
            DBMS_OUTPUT.PUT_LINE('Kept existing index ' || UPPER(index_name_in));
        END IF;
    END;
BEGIN
    create_table_if_missing('sync_jobs', q'[
        CREATE TABLE sync_jobs (
            id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
            file_hash   VARCHAR2(64 CHAR) NOT NULL,
            status      VARCHAR2(32 CHAR) NOT NULL,
            created_at  TIMESTAMP(6) NOT NULL,
            updated_at  TIMESTAMP(6),
            CONSTRAINT pk_sync_jobs PRIMARY KEY (id),
            CONSTRAINT uk_sync_jobs_file_hash UNIQUE (file_hash)
        )
    ]');

    create_table_if_missing('file_records', q'[
        CREATE TABLE file_records (
            id                  NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
            sync_job_id         NUMBER(19,0) NOT NULL,
            source_type         VARCHAR2(32 CHAR) NOT NULL,
            original_file_name  VARCHAR2(255 CHAR) NOT NULL,
            stored_path         VARCHAR2(255 CHAR) NOT NULL,
            processing_status   VARCHAR2(32 CHAR) DEFAULT 'DISCOVERED' NOT NULL,
            rows_saved          NUMBER(10,0),
            downloaded_at       TIMESTAMP(6),
            database_saved_at   TIMESTAMP(6),
            archive_status      VARCHAR2(32 CHAR) DEFAULT 'PENDING' NOT NULL,
            archived_at         TIMESTAMP(6),
            error_message       VARCHAR2(2000 CHAR),
            file_size           NUMBER(19,0),
            checksum            VARCHAR2(64 CHAR),
            created_at          TIMESTAMP(6) NOT NULL,
            CONSTRAINT pk_file_records PRIMARY KEY (id),
            CONSTRAINT fk_file_records_sync_job
                FOREIGN KEY (sync_job_id) REFERENCES sync_jobs(id)
        )
    ]');

    create_table_if_missing('email_metadata', q'[
        CREATE TABLE email_metadata (
            id                      NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
            sync_job_id             NUMBER(19,0),
            message_id              VARCHAR2(255 CHAR) NOT NULL,
            mailbox_folder          VARCHAR2(255 CHAR),
            uid_validity            NUMBER(19,0),
            message_uid             NUMBER(19,0),
            attachment_index        NUMBER(10,0),
            attachment_name         VARCHAR2(255 CHAR),
            sender                  VARCHAR2(255 CHAR),
            subject                 VARCHAR2(255 CHAR),
            received_at             TIMESTAMP(6),
            attachment_count        NUMBER(10,0) NOT NULL,
            body                    CLOB,
            processing_status       VARCHAR2(32 CHAR) DEFAULT 'DISCOVERED' NOT NULL,
            acknowledgement_status  VARCHAR2(32 CHAR) DEFAULT 'PENDING' NOT NULL,
            ingest_complete         NUMBER(1,0) DEFAULT 0 NOT NULL,
            acknowledged_at         TIMESTAMP(6),
            acknowledgement_error   VARCHAR2(2000 CHAR),
            CONSTRAINT pk_email_metadata PRIMARY KEY (id),
            CONSTRAINT fk_email_metadata_sync_job
                FOREIGN KEY (sync_job_id) REFERENCES sync_jobs(id),
            CONSTRAINT uk_email_mailbox_attachment
                UNIQUE (mailbox_folder, uid_validity, message_uid, attachment_index),
            CONSTRAINT ck_email_ingest_complete
                CHECK (ingest_complete IN (0, 1))
        )
    ]');

    create_table_if_missing('audit_logs', q'[
        CREATE TABLE audit_logs (
            id              NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
            sync_job_id     NUMBER(19,0),
            action          VARCHAR2(100 CHAR) NOT NULL,
            input_summary   CLOB,
            output_summary  CLOB,
            duration_ms     NUMBER(19,0),
            result_status   VARCHAR2(32 CHAR) NOT NULL,
            timestamp       TIMESTAMP(6) NOT NULL,
            CONSTRAINT pk_audit_logs PRIMARY KEY (id),
            CONSTRAINT fk_audit_logs_sync_job
                FOREIGN KEY (sync_job_id) REFERENCES sync_jobs(id)
        )
    ]');

    create_table_if_missing('permit_imports', q'[
        CREATE TABLE permit_imports (
            id                    NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
            sync_job_id           NUMBER(19,0) NOT NULL,
            normalized_permit_id  VARCHAR2(100 CHAR) NOT NULL,
            semantic_hash         VARCHAR2(64 CHAR) NOT NULL,
            source_file_hash      VARCHAR2(64 CHAR) NOT NULL,
            status                VARCHAR2(32 CHAR) NOT NULL,
            target_master_id      NUMBER(19,0),
            target_perm_id        NUMBER(19,0),
            detail_count          NUMBER(10,0),
            error_message         VARCHAR2(2000 CHAR),
            created_at            TIMESTAMP(6) NOT NULL,
            updated_at            TIMESTAMP(6) NOT NULL,
            CONSTRAINT pk_permit_imports PRIMARY KEY (id),
            CONSTRAINT uk_permit_imports_sync_job UNIQUE (sync_job_id),
            CONSTRAINT fk_permit_imports_sync_job
                FOREIGN KEY (sync_job_id) REFERENCES sync_jobs(id)
        )
    ]');

    create_sequence_if_missing(
        'flight_data_seq',
        'CREATE SEQUENCE flight_data_seq START WITH 1 INCREMENT BY 50 CACHE 50 NOCYCLE'
    );

    create_table_if_missing('flight_data', q'[
        CREATE TABLE flight_data (
            id            NUMBER(19,0) NOT NULL,
            sync_job_id   NUMBER(19,0) NOT NULL,
            callsign      VARCHAR2(16 CHAR) NOT NULL,
            from_airport  VARCHAR2(3 CHAR) NOT NULL,
            to_airport    VARCHAR2(3 CHAR) NOT NULL,
            date_flight   DATE NOT NULL,
            created_at    TIMESTAMP(6) NOT NULL,
            CONSTRAINT pk_flight_data PRIMARY KEY (id),
            CONSTRAINT fk_flight_data_sync_job
                FOREIGN KEY (sync_job_id) REFERENCES sync_jobs(id)
        )
    ]');

    create_table_if_missing('dashboard_alerts', q'[
        CREATE TABLE dashboard_alerts (
            id               NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
            sync_job_id      NUMBER(19,0),
            status           VARCHAR2(32 CHAR) NOT NULL,
            alert_level      VARCHAR2(16 CHAR) NOT NULL,
            message          VARCHAR2(2000 CHAR) NOT NULL,
            event_timestamp  TIMESTAMP(6),
            created_at       TIMESTAMP(6) NOT NULL,
            resolved         NUMBER(1,0) DEFAULT 0 NOT NULL,
            CONSTRAINT pk_dashboard_alerts PRIMARY KEY (id),
            CONSTRAINT fk_dashboard_alerts_sync_job
                FOREIGN KEY (sync_job_id) REFERENCES sync_jobs(id),
            CONSTRAINT ck_dashboard_alerts_resolved
                CHECK (resolved IN (0, 1))
        )
    ]');

    create_table_if_missing('runtime_config', q'[
        CREATE TABLE runtime_config (
            id                          NUMBER(19,0) NOT NULL,
            scheduler_fixed_delay_ms    NUMBER(19,0) NOT NULL,
            max_files_per_cycle         NUMBER(10,0) NOT NULL,
            incoming_dir                VARCHAR2(255 CHAR) NOT NULL,
            processed_dir               VARCHAR2(255 CHAR) NOT NULL,
            error_dir                   VARCHAR2(255 CHAR) NOT NULL,
            email_host                  VARCHAR2(255 CHAR) NOT NULL,
            email_port                  NUMBER(10,0) NOT NULL,
            email_protocol              VARCHAR2(255 CHAR) NOT NULL,
            email_user                  VARCHAR2(255 CHAR) NOT NULL,
            email_password              VARCHAR2(255 CHAR),
            retry_mode                  VARCHAR2(255 CHAR) NOT NULL,
            max_size_per_file_mb        NUMBER(10,0) NOT NULL,
            auto_quarantine             NUMBER(1,0) DEFAULT 0 NOT NULL,
            skip_duplicate_idempotency  NUMBER(1,0) DEFAULT 0 NOT NULL,
            send_zalo_alert             NUMBER(1,0) DEFAULT 0 NOT NULL,
            CONSTRAINT pk_runtime_config PRIMARY KEY (id),
            CONSTRAINT ck_runtime_auto_quarantine
                CHECK (auto_quarantine IN (0, 1)),
            CONSTRAINT ck_runtime_skip_duplicate
                CHECK (skip_duplicate_idempotency IN (0, 1)),
            CONSTRAINT ck_runtime_config_send_zalo
                CHECK (send_zalo_alert IN (0, 1))
        )
    ]');

    create_table_if_missing('runtime_config_blacklist', q'[
        CREATE TABLE runtime_config_blacklist (
            config_id  NUMBER(19,0) NOT NULL,
            sender     VARCHAR2(255 CHAR),
            CONSTRAINT fk_runtime_blacklist_config
                FOREIGN KEY (config_id) REFERENCES runtime_config(id)
        )
    ]');

    create_index_if_missing(
        'ix_file_records_sync_job',
        'CREATE INDEX ix_file_records_sync_job ON file_records(sync_job_id)'
    );
    create_index_if_missing(
        'ix_email_metadata_sync_job',
        'CREATE INDEX ix_email_metadata_sync_job ON email_metadata(sync_job_id)'
    );
    create_index_if_missing(
        'ix_email_metadata_received',
        'CREATE INDEX ix_email_metadata_received ON email_metadata(received_at)'
    );
    create_index_if_missing(
        'ix_email_metadata_status',
        'CREATE INDEX ix_email_metadata_status ON email_metadata(processing_status)'
    );
    create_index_if_missing(
        'ix_audit_logs_sync_job',
        'CREATE INDEX ix_audit_logs_sync_job ON audit_logs(sync_job_id)'
    );
    create_index_if_missing(
        'ix_audit_logs_timestamp',
        'CREATE INDEX ix_audit_logs_timestamp ON audit_logs(timestamp)'
    );
    create_index_if_missing(
        'ix_permit_import_status',
        'CREATE INDEX ix_permit_import_status ' ||
        'ON permit_imports(normalized_permit_id, status)'
    );
    create_index_if_missing(
        'ix_flight_data_sync_job',
        'CREATE INDEX ix_flight_data_sync_job ON flight_data(sync_job_id)'
    );
    create_index_if_missing(
        'ix_dashboard_alerts_job',
        'CREATE INDEX ix_dashboard_alerts_job ON dashboard_alerts(sync_job_id)'
    );
    create_index_if_missing(
        'ix_dashboard_alerts_resolved',
        'CREATE INDEX ix_dashboard_alerts_resolved ON dashboard_alerts(resolved, created_at)'
    );
    create_index_if_missing(
        'ix_runtime_blacklist_config',
        'CREATE INDEX ix_runtime_blacklist_config ON runtime_config_blacklist(config_id)'
    );
END;
/

PROMPT
PROMPT AeroSync Oracle schema initialization completed.
PROMPT Existing ATFM tables were not changed.
PROMPT

SELECT table_name
  FROM user_tables
 WHERE table_name IN (
       'SYNC_JOBS',
       'FILE_RECORDS',
       'EMAIL_METADATA',
       'AUDIT_LOGS',
       'PERMIT_IMPORTS',
       'FLIGHT_DATA',
       'DASHBOARD_ALERTS',
       'RUNTIME_CONFIG',
       'RUNTIME_CONFIG_BLACKLIST'
 )
 ORDER BY table_name;

EXIT SUCCESS
