WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO OFF
SET FEEDBACK ON

DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO table_count
      FROM user_tables
     WHERE table_name = 'APP_USERS';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE app_users (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR2(100) NOT NULL,
                password_hash VARCHAR2(100) NOT NULL,
                role VARCHAR2(32) NOT NULL,
                enabled NUMBER(1) DEFAULT 1 NOT NULL,
                created_at TIMESTAMP(6) NOT NULL,
                updated_at TIMESTAMP(6) NOT NULL,
                CONSTRAINT uk_app_users_username UNIQUE (username),
                CONSTRAINT ck_app_users_role CHECK (role IN ('OPERATOR', 'ADMIN')),
                CONSTRAINT ck_app_users_enabled CHECK (enabled IN (0, 1))
            )
        ]';
    END IF;

    SELECT COUNT(*)
      INTO table_count
      FROM user_tables
     WHERE table_name = 'PERMIT_REVIEWS';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE permit_reviews (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                permit_import_id NUMBER NOT NULL,
                status VARCHAR2(32) NOT NULL,
                profile_id VARCHAR2(120),
                profile_version NUMBER(10),
                confidence BINARY_DOUBLE,
                runner_up_margin BINARY_DOUBLE,
                review_reason VARCHAR2(2000),
                original_permit_json CLOB NOT NULL,
                corrected_permit_json CLOB,
                published_permit_json CLOB,
                profile_candidates_json CLOB,
                field_diagnostics_json CLOB,
                warnings_json CLOB,
                correction_comment VARCHAR2(2000),
                corrected_by VARCHAR2(100),
                corrected_at TIMESTAMP(6),
                approval_comment VARCHAR2(2000),
                approved_by VARCHAR2(100),
                approved_at TIMESTAMP(6),
                rejection_reason VARCHAR2(2000),
                rejected_by VARCHAR2(100),
                rejected_at TIMESTAMP(6),
                publish_requested_by VARCHAR2(100),
                publish_requested_at TIMESTAMP(6),
                published_by VARCHAR2(100),
                published_at TIMESTAMP(6),
                publish_error VARCHAR2(2000),
                version NUMBER(19) DEFAULT 0 NOT NULL,
                created_at TIMESTAMP(6) NOT NULL,
                updated_at TIMESTAMP(6) NOT NULL,
                CONSTRAINT uk_permit_reviews_import UNIQUE (permit_import_id),
                CONSTRAINT fk_permit_reviews_import
                    FOREIGN KEY (permit_import_id) REFERENCES permit_imports(id),
                CONSTRAINT ck_permit_reviews_status CHECK (
                    status IN (
                        'PENDING',
                        'CORRECTED',
                        'APPROVED',
                        'PUBLISHING',
                        'PUBLISHED',
                        'REJECTED',
                        'PUBLISH_FAILED'
                    )
                )
            )
        ]';
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_permit_reviews_status_created ' ||
            'ON permit_reviews(status, created_at)';
    END IF;
END;
/

PROMPT Adaptive permit review migration completed.
PROMPT Configure APP_BOOTSTRAP_ADMIN_USERNAME and APP_BOOTSTRAP_ADMIN_PASSWORD
PROMPT for the API's first startup, then remove those values after the account is created.
EXIT SUCCESS
