WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO OFF
SET FEEDBACK ON

DECLARE
    table_count NUMBER;
    column_count NUMBER;
    constraint_count NUMBER;
    index_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO table_count
      FROM user_tables
     WHERE table_name IN ('T_USERS', 'T_USERMENU');

    IF table_count <> 2 THEN
        RAISE_APPLICATION_ERROR(
                -20001,
                'Legacy T_USERS and T_USERMENU tables are required');
    END IF;

    SELECT COUNT(*)
      INTO table_count
      FROM user_tables
     WHERE table_name = 'PERMIT_REVIEWS';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE permit_reviews (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                permit_import_id NUMBER NOT NULL,
                status VARCHAR2(32) NOT NULL,
                profile_id VARCHAR2(120),
                profile_version NUMBER(10),
                confidence BINARY_DOUBLE,
                runner_up_margin BINARY_DOUBLE,
                review_reason VARCHAR2(2000),
                original_permit_json CLOB NOT NULL,
                corrected_permit_json CLOB,
                published_permit_json CLOB,
                profile_candidates_json CLOB,
                field_diagnostics_json CLOB,
                warnings_json CLOB,
                correction_comment VARCHAR2(2000),
                corrected_by VARCHAR2(100),
                corrected_at TIMESTAMP(6),
                approval_comment VARCHAR2(2000),
                approved_by VARCHAR2(100),
                approved_at TIMESTAMP(6),
                rejection_reason VARCHAR2(2000),
                rejected_by VARCHAR2(100),
                rejected_at TIMESTAMP(6),
                publish_requested_by VARCHAR2(100),
                publish_requested_at TIMESTAMP(6),
                published_by VARCHAR2(100),
                published_at TIMESTAMP(6),
                publish_error VARCHAR2(2000),
                version NUMBER(19) DEFAULT 0 NOT NULL,
                created_at TIMESTAMP(6) NOT NULL,
                updated_at TIMESTAMP(6) NOT NULL,
                CONSTRAINT uk_permit_reviews_import UNIQUE (permit_import_id),
                CONSTRAINT fk_permit_reviews_import
                    FOREIGN KEY (permit_import_id) REFERENCES permit_imports(id),
                CONSTRAINT ck_permit_reviews_status CHECK (
                    status IN (
                        'PENDING',
                        'CORRECTED',
                        'APPROVED',
                        'PUBLISHING',
                        'PUBLISHED',
                        'REJECTED',
                        'PUBLISH_FAILED'
                    )
                )
            )
        ]';
    END IF;

    SELECT COUNT(*)
      INTO index_count
      FROM user_indexes
     WHERE index_name IN (
        'IX_PERMIT_REVIEWS_STATUS_CREATED',
        'IX_REVIEW_STATUS_CREATED'
     );
    IF index_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_review_status_created ' ||
            'ON permit_reviews(status, created_at)';
    END IF;

    SELECT COUNT(*)
      INTO table_count
      FROM user_tables
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE permit_training_candidates (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                permit_review_id NUMBER NOT NULL,
                status VARCHAR2(32) NOT NULL,
                profile_id VARCHAR2(120) NOT NULL,
                profile_version NUMBER(10) NOT NULL,
                semantic_field VARCHAR2(120) NOT NULL,
                alias_value VARCHAR2(500) NOT NULL,
                canonical_alias VARCHAR2(500) NOT NULL,
                match_method VARCHAR2(32) NOT NULL,
                confidence BINARY_DOUBLE NOT NULL,
                proposed_by VARCHAR2(100),
                decision_comment VARCHAR2(2000),
                decided_by VARCHAR2(100),
                decided_at TIMESTAMP(6),
                usage_count NUMBER(19) DEFAULT 0 NOT NULL,
                last_used_at TIMESTAMP(6),
                validation_status VARCHAR2(32) DEFAULT 'NOT_RUN' NOT NULL,
                validation_requested_by VARCHAR2(100),
                validation_requested_at TIMESTAMP(6),
                validation_completed_at TIMESTAMP(6),
                validation_corpus_size NUMBER(10),
                validation_passed_count NUMBER(10),
                validation_failed_count NUMBER(10),
                validation_report VARCHAR2(4000),
                version NUMBER(19) DEFAULT 0 NOT NULL,
                created_at TIMESTAMP(6) NOT NULL,
                updated_at TIMESTAMP(6) NOT NULL,
                CONSTRAINT uk_training_review_field UNIQUE (
                    permit_review_id,
                    semantic_field,
                    canonical_alias
                ),
                CONSTRAINT fk_training_review
                    FOREIGN KEY (permit_review_id) REFERENCES permit_reviews(id),
                CONSTRAINT ck_training_status CHECK (
                    status IN ('PENDING', 'APPROVED', 'REJECTED', 'DISABLED')
                ),
                CONSTRAINT ck_training_validation_status CHECK (
                    validation_status IN (
                        'NOT_RUN', 'RUNNING', 'PASSED', 'FAILED'
                    )
                )
            )
        ]';
    END IF;

    SELECT COUNT(*)
      INTO index_count
      FROM user_indexes
     WHERE index_name = 'IX_TRAINING_STATUS_CREATED';
    IF index_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_training_status_created ' ||
            'ON permit_training_candidates(status, created_at)';
    END IF;

    SELECT COUNT(*)
      INTO index_count
      FROM user_indexes
     WHERE index_name = 'IX_TRAINING_PROFILE_ALIAS';
    IF index_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_training_profile_alias ' ||
            'ON permit_training_candidates(profile_id, canonical_alias)';
    END IF;

    SELECT COUNT(*)
      INTO column_count
      FROM user_tab_columns
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND column_name = 'USAGE_COUNT';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ADD (' ||
            'usage_count NUMBER(19) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*)
      INTO column_count
      FROM user_tab_columns
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND column_name = 'LAST_USED_AT';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ADD (' ||
            'last_used_at TIMESTAMP(6))';
    END IF;

    SELECT COUNT(*)
      INTO column_count
      FROM user_tab_columns
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND column_name = 'VALIDATION_STATUS';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ADD (' ||
            'validation_status VARCHAR2(32) DEFAULT ''NOT_RUN'' NOT NULL)';
    END IF;

    SELECT COUNT(*)
      INTO column_count
      FROM user_tab_columns
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND column_name = 'VALIDATION_REQUESTED_BY';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ADD (' ||
            'validation_requested_by VARCHAR2(100))';
    END IF;

    SELECT COUNT(*)
      INTO column_count
      FROM user_tab_columns
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND column_name = 'VALIDATION_REQUESTED_AT';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ADD (' ||
            'validation_requested_at TIMESTAMP(6))';
    END IF;

    SELECT COUNT(*)
      INTO column_count
      FROM user_tab_columns
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND column_name = 'VALIDATION_COMPLETED_AT';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ADD (' ||
            'validation_completed_at TIMESTAMP(6))';
    END IF;

    SELECT COUNT(*)
      INTO column_count
      FROM user_tab_columns
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND column_name = 'VALIDATION_CORPUS_SIZE';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ADD (' ||
            'validation_corpus_size NUMBER(10))';
    END IF;

    SELECT COUNT(*)
      INTO column_count
      FROM user_tab_columns
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND column_name = 'VALIDATION_PASSED_COUNT';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ADD (' ||
            'validation_passed_count NUMBER(10))';
    END IF;

    SELECT COUNT(*)
      INTO column_count
      FROM user_tab_columns
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND column_name = 'VALIDATION_FAILED_COUNT';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ADD (' ||
            'validation_failed_count NUMBER(10))';
    END IF;

    SELECT COUNT(*)
      INTO column_count
      FROM user_tab_columns
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND column_name = 'VALIDATION_REPORT';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ADD (' ||
            'validation_report VARCHAR2(4000))';
    END IF;

    SELECT COUNT(*)
      INTO constraint_count
      FROM user_constraints
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND constraint_name = 'CK_TRAINING_STATUS';
    IF constraint_count > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ' ||
            'DROP CONSTRAINT ck_training_status';
    END IF;
    EXECUTE IMMEDIATE
        'ALTER TABLE permit_training_candidates ' ||
        'ADD CONSTRAINT ck_training_status CHECK (' ||
        'status IN (''PENDING'', ''APPROVED'', ''REJECTED'', ''DISABLED''))';

    SELECT COUNT(*)
      INTO constraint_count
      FROM user_constraints
     WHERE table_name = 'PERMIT_TRAINING_CANDIDATES'
       AND constraint_name = 'CK_TRAINING_VALIDATION_STATUS';
    IF constraint_count > 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE permit_training_candidates ' ||
            'DROP CONSTRAINT ck_training_validation_status';
    END IF;
    EXECUTE IMMEDIATE
        'ALTER TABLE permit_training_candidates ' ||
        'ADD CONSTRAINT ck_training_validation_status CHECK (' ||
        'validation_status IN (' ||
        '''NOT_RUN'', ''RUNNING'', ''PASSED'', ''FAILED''))';

    SELECT COUNT(*)
      INTO table_count
      FROM user_tables
     WHERE table_name = 'PERMIT_TRAINING_DECISIONS';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE permit_training_decisions (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                candidate_id NUMBER NOT NULL,
                action VARCHAR2(32) NOT NULL,
                actor VARCHAR2(100) NOT NULL,
                decision_comment VARCHAR2(2000),
                created_at TIMESTAMP(6) NOT NULL,
                CONSTRAINT fk_training_decision_candidate
                    FOREIGN KEY (candidate_id)
                    REFERENCES permit_training_candidates(id),
                CONSTRAINT ck_training_decision_action CHECK (
                    action IN (
                        'APPROVED',
                        'REJECTED',
                        'DISABLED',
                        'REACTIVATED',
                        'VALIDATION_REQUESTED',
                        'VALIDATION_PASSED',
                        'VALIDATION_FAILED'
                    )
                )
            )
        ]';
    END IF;

    SELECT COUNT(*)
      INTO index_count
      FROM user_indexes
     WHERE index_name = 'IX_TRAINING_DECISION_CANDIDATE';
    IF index_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_training_decision_candidate ' ||
            'ON permit_training_decisions(candidate_id, created_at)';
    END IF;

    SELECT COUNT(*)
      INTO table_count
      FROM user_tables
     WHERE table_name = 'PERMIT_TRAINING_SOURCES';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE permit_training_sources (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                file_record_id NUMBER NOT NULL,
                state VARCHAR2(32) NOT NULL,
                source_hash VARCHAR2(64) NOT NULL,
                original_file_name VARCHAR2(500) NOT NULL,
                document_json CLOB,
                parse_error VARCHAR2(2000),
                profile_id VARCHAR2(120),
                profile_version NUMBER(10),
                confidence BINARY_DOUBLE,
                corpus_path VARCHAR2(1000),
                retained_at TIMESTAMP(6),
                version NUMBER(19) DEFAULT 0 NOT NULL,
                created_at TIMESTAMP(6) NOT NULL,
                updated_at TIMESTAMP(6) NOT NULL,
                CONSTRAINT uk_training_source_file UNIQUE (file_record_id),
                CONSTRAINT fk_training_source_file
                    FOREIGN KEY (file_record_id) REFERENCES file_records(id),
                CONSTRAINT ck_training_source_state CHECK (
                    state IN (
                        'PROCESSING',
                        'PARSED',
                        'REVIEW_REQUIRED',
                        'FAILED',
                        'QUARANTINED'
                    )
                )
            )
        ]';
    END IF;

    SELECT COUNT(*)
      INTO index_count
      FROM user_indexes
     WHERE index_name = 'IX_TRAINING_SOURCE_STATE';
    IF index_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_training_source_state ' ||
            'ON permit_training_sources(state, created_at)';
    END IF;

    SELECT COUNT(*)
      INTO index_count
      FROM user_indexes
     WHERE index_name = 'IX_TRAINING_SOURCE_HASH';
    IF index_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_training_source_hash ' ||
            'ON permit_training_sources(source_hash)';
    END IF;

    SELECT COUNT(*)
      INTO table_count
      FROM user_tables
     WHERE table_name = 'PERMIT_TRAINING_PROFILES';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE permit_training_profiles (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                profile_key VARCHAR2(120) NOT NULL,
                profile_version NUMBER(10) NOT NULL,
                status VARCHAR2(32) NOT NULL,
                base_profile_id VARCHAR2(120),
                base_profile_version NUMBER(10),
                schema_version NUMBER(10) DEFAULT 1 NOT NULL,
                definition_json CLOB,
                compiled_profile_json CLOB,
                definition_checksum VARCHAR2(64),
                evidence_count NUMBER(10) DEFAULT 0 NOT NULL,
                canary_success_count NUMBER(10) DEFAULT 0 NOT NULL,
                created_by VARCHAR2(100) NOT NULL,
                confirmed_by VARCHAR2(100),
                confirmed_at TIMESTAMP(6),
                last_error VARCHAR2(2000),
                version NUMBER(19) DEFAULT 0 NOT NULL,
                created_at TIMESTAMP(6) NOT NULL,
                updated_at TIMESTAMP(6) NOT NULL,
                CONSTRAINT uk_training_profile_version UNIQUE (
                    profile_key,
                    profile_version
                ),
                CONSTRAINT ck_training_profile_status CHECK (
                    status IN (
                        'DRAFT',
                        'COLLECTING_EVIDENCE',
                        'VALIDATING',
                        'CANARY',
                        'ACTIVE',
                        'NEEDS_REVISION',
                        'DISABLED',
                        'REJECTED'
                    )
                )
            )
        ]';
    END IF;

    SELECT COUNT(*)
      INTO index_count
      FROM user_indexes
     WHERE index_name = 'IX_TRAINING_PROFILE_STATUS';
    IF index_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_training_profile_status ' ||
            'ON permit_training_profiles(status, updated_at)';
    END IF;

    SELECT COUNT(*)
      INTO table_count
      FROM user_tables
     WHERE table_name = 'PERMIT_TRAINING_EVIDENCE';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE permit_training_evidence (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                training_profile_id NUMBER NOT NULL,
                training_source_id NUMBER NOT NULL,
                permit_review_id NUMBER,
                kind VARCHAR2(32) NOT NULL,
                result VARCHAR2(32) NOT NULL,
                expected_snapshot_json CLOB,
                actor VARCHAR2(100),
                evaluated_at TIMESTAMP(6),
                detail VARCHAR2(2000),
                created_at TIMESTAMP(6) NOT NULL,
                CONSTRAINT uk_training_profile_source UNIQUE (
                    training_profile_id,
                    training_source_id
                ),
                CONSTRAINT fk_training_evidence_profile
                    FOREIGN KEY (training_profile_id)
                    REFERENCES permit_training_profiles(id),
                CONSTRAINT fk_training_evidence_source
                    FOREIGN KEY (training_source_id)
                    REFERENCES permit_training_sources(id),
                CONSTRAINT fk_training_evidence_review
                    FOREIGN KEY (permit_review_id)
                    REFERENCES permit_reviews(id),
                CONSTRAINT ck_training_evidence_kind CHECK (
                    kind IN ('TRAINING', 'CANARY')
                ),
                CONSTRAINT ck_training_evidence_result CHECK (
                    result IN (
                        'PENDING',
                        'PASSED',
                        'CORRECTED',
                        'REJECTED',
                        'FAILED'
                    )
                )
            )
        ]';
    END IF;

    SELECT COUNT(*)
      INTO index_count
      FROM user_indexes
     WHERE index_name = 'IX_TRAINING_EVIDENCE_PROFILE';
    IF index_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_training_evidence_profile ' ||
            'ON permit_training_evidence(training_profile_id, created_at)';
    END IF;

    SELECT COUNT(*)
      INTO table_count
      FROM user_tables
     WHERE table_name = 'PERMIT_TRAINING_PROFILE_EVENTS';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE permit_training_profile_events (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                training_profile_id NUMBER NOT NULL,
                action VARCHAR2(32) NOT NULL,
                actor VARCHAR2(100) NOT NULL,
                event_detail CLOB,
                created_at TIMESTAMP(6) NOT NULL,
                CONSTRAINT fk_training_event_profile
                    FOREIGN KEY (training_profile_id)
                    REFERENCES permit_training_profiles(id)
            )
        ]';
    END IF;

    SELECT COUNT(*)
      INTO index_count
      FROM user_indexes
     WHERE index_name = 'IX_TRAINING_EVENT_PROFILE';
    IF index_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_training_event_profile ' ||
            'ON permit_training_profile_events(' ||
            'training_profile_id, created_at)';
    END IF;
END;
/

PROMPT Adaptive permit review and training promotion migration completed.
PROMPT Phase 1 guided profile training foundation migration completed.
PROMPT Review authentication uses active legacy T_USERS accounts.
EXIT SUCCESS
