WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO OFF
SET FEEDBACK ON

DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO table_count
      FROM user_tables
     WHERE table_name = 'PERMIT_IMPORTS';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE permit_imports (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sync_job_id NUMBER NOT NULL,
                normalized_permit_id VARCHAR2(100) NOT NULL,
                semantic_hash VARCHAR2(64) NOT NULL,
                source_file_hash VARCHAR2(64) NOT NULL,
                status VARCHAR2(32) NOT NULL,
                target_master_id NUMBER,
                target_perm_id NUMBER,
                detail_count NUMBER(10),
                error_message VARCHAR2(2000),
                created_at TIMESTAMP(6) NOT NULL,
                updated_at TIMESTAMP(6) NOT NULL,
                CONSTRAINT uk_permit_imports_sync_job UNIQUE (sync_job_id),
                CONSTRAINT fk_permit_imports_sync_job
                    FOREIGN KEY (sync_job_id) REFERENCES sync_jobs(id)
            )
        ]';
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_permit_imports_permit_status ' ||
            'ON permit_imports(normalized_permit_id, status)';
    END IF;
END;
/

PROMPT Phase 5 Oracle permit-import tracking migration completed.
EXIT SUCCESS
